host: 181.215.37.10
port: 3306
database: s1629_prisoncore
username: u1629_bqHnTwUbYb
password: IWLaibRzrw8Kr!IJEMXW7x.3

reset_character:
  commands_before_nick_name: # commands to run when he just starts the reset character process (do stuff such as reset levels / clan etc)
    - "reset level %player%" # not a real command
  guis:
    clan_choose_gui:
      rows: 3
      items:
        uchia:
          name: "&cUchia Clan"
          type: "diamond"
          slot: 13
          commands_to_run:
            - "msg %player% you chose your clan"
          lore:
            - "&cBeaware of the Uchia curse"
            - "&cWhen a man learns to love he must also bear the risk of hatred..."
    chakra_nature:
      rows: 3
      items:
        uchia:
          name: "&bWater"
          type: "water_bucket"
          slot: 13
          commands_to_run:
            - "msg %player% you finished choosing a chakara nature"
          lore:
            - "&bThe water element is fierce!"
    specialization:
      rows: 3
      items:
        uchia:
          name: "&3Genjutsu"
          type: "emerald"
          slot: 13
          commands_to_run:
            - "msg %player% you finish specializing"
          lore:
            - "&bThe water element is fierce!"
